### PR TITLE
DynamicClassCreator: Use self.res

### PR DESCRIPTION
**Pull request by myakove**
DynamicClassCreator: use self.res to match https://github.com/RedHatQE/openshift-python-wrapper/pull/945

### CODE REVIEW

**Comment by myakove** [comment]
Depends on https://github.com/RedHatQE/openshift-python-wrapper/pull/945

**Review by rnetser — APPROVED** [review]

**Comment by myakove** [comment]
!verified

**Comment by myakove** [comment]
!cherry-pick v4.12

**Comment by myakove** [comment]
!cherry-pick v4.12

**Comment by myakove** [comment]
!cherry-pick v4.12

**Comment by myakove** [comment]
!cherry-pick v4.12

**Pull request merged**
